from __future__ import annotations

import json
import re
from textwrap import shorten
from urllib import request
from urllib.error import HTTPError, URLError
from json import JSONDecodeError

from lexicon.ai.base import AIProvider
from lexicon.config import AppConfig


class LocalProvider(AIProvider):
    """Deterministic fallback for offline development and tests."""

    def complete(self, system: str, user: str) -> str:
        _ = system
        if "Return ONLY valid JSON" in user:
            title = _extract_prompt_field(user, "Preferred title") or "Untitled"
            source = _extract_prompt_field(user, "Source")
            raw = user.split("Raw extracted markdown:", 1)[-1].strip()
            body = (
                f"# {title}\n\n"
                f"{shorten(' '.join(raw.split()), width=800, placeholder='...')}\n\n"
                "## Review notes\n"
                "- Generated by the local fallback provider; review before using as authoritative knowledge.\n"
            )
            return json.dumps(
                {
                    "title": title,
                    "suggested_folder": "concepts",
                    "tags": [],
                    "confidence": 0.65,
                    "expires_at": "",
                    "warnings": [f"Local fallback used for source: {source or 'unknown'}"],
                    "body": body,
                },
                ensure_ascii=False,
            )
        body = user.strip()
        return (
            "## Summary\n"
            f"{shorten(' '.join(body.split()), width=700, placeholder='...')}\n\n"
            "## Review notes\n"
            "- Generated by the local fallback provider; review before using as authoritative knowledge.\n"
        )


class OpenAICompatibleProvider(AIProvider):
    def __init__(self, config: AppConfig) -> None:
        if not config.base_url and config.provider == "openai":
            config.base_url = "https://api.openai.com/v1"
        if not config.base_url:
            raise ValueError("base_url is required for this provider")
        if not config.api_key:
            raise ValueError(f"API key env var is not set: {config.api_key_env}")
        self.config = config

    def complete(self, system: str, user: str) -> str:
        url = self.config.base_url.rstrip("/") + "/chat/completions"
        payload = {
            "model": self.config.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": 0.2,
        }
        data = _post_json(
            url,
            payload,
            {
                "Authorization": f"Bearer {self.config.api_key}",
                "Content-Type": "application/json",
            },
            timeout=90,
        )
        if "__stream_text" in data:
            return data["__stream_text"]
        return data["choices"][0]["message"]["content"]


class AnthropicProvider(AIProvider):
    def __init__(self, config: AppConfig) -> None:
        if not config.api_key:
            raise ValueError(f"API key env var is not set: {config.api_key_env}")
        self.config = config

    def complete(self, system: str, user: str) -> str:
        url = (self.config.base_url or "https://api.anthropic.com/v1").rstrip("/") + "/messages"
        payload = {
            "model": self.config.model,
            "system": system,
            "messages": [{"role": "user", "content": user}],
            "max_tokens": 4096,
            "temperature": 0.2,
        }
        data = _post_json(
            url,
            payload,
            {
                "x-api-key": self.config.api_key or "",
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json",
            },
            timeout=90,
        )
        return "".join(block.get("text", "") for block in data.get("content", []))


class OllamaProvider(AIProvider):
    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self.base_url = (config.base_url or "http://localhost:11434").rstrip("/")

    def complete(self, system: str, user: str) -> str:
        data = _post_json(
            self.base_url + "/api/chat",
            {
                "model": self.config.model,
                "stream": False,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
            },
            {"Content-Type": "application/json"},
            timeout=180,
        )
        return data.get("message", {}).get("content", "")


def build_provider(config: AppConfig | None = None) -> AIProvider:
    config = config or AppConfig.load()
    if config.provider in {"local", "", None}:
        return LocalProvider()
    if config.provider in {"openai", "openrouter", "gemini", "openai-compatible"}:
        return OpenAICompatibleProvider(config)
    if config.provider == "anthropic":
        return AnthropicProvider(config)
    if config.provider == "ollama":
        return OllamaProvider(config)
    raise ValueError(f"Unsupported provider: {config.provider}")


def _extract_prompt_field(prompt: str, field: str) -> str:
    match = re.search(rf"^{re.escape(field)}:\s*(.*)$", prompt, flags=re.M)
    return match.group(1).strip() if match else ""


def _post_json(url: str, payload: dict, headers: dict[str, str], timeout: int) -> dict:
    body = json.dumps(payload).encode("utf-8")
    req = request.Request(url, data=body, headers=headers, method="POST")
    try:
        with request.urlopen(req, timeout=timeout) as response:
            raw = response.read().decode("utf-8", errors="replace")
            if raw.lstrip().startswith("data:"):
                return {"__stream_text": _parse_sse_chat_completion(raw)}
            try:
                return json.loads(raw)
            except JSONDecodeError as exc:
                preview = raw[:500] if raw else "<empty response>"
                raise RuntimeError(f"AI provider returned non-JSON response from {url}: {preview}") from exc
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} from AI provider: {detail}") from exc
    except URLError as exc:
        reason = getattr(exc, "reason", exc)
        raise RuntimeError(f"AI provider is not reachable at {url}: {reason}") from exc


def _parse_sse_chat_completion(raw: str) -> str:
    chunks: list[str] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line.startswith("data:"):
            continue
        data = line[5:].strip()
        if not data or data == "[DONE]":
            continue
        try:
            event = json.loads(data)
        except JSONDecodeError:
            continue
        for choice in event.get("choices", []):
            delta = choice.get("delta") or {}
            if "content" in delta:
                chunks.append(delta["content"])
            message = choice.get("message") or {}
            if "content" in message:
                chunks.append(message["content"])
    if not chunks:
        raise RuntimeError("AI provider returned SSE response without text content.")
    return "".join(chunks)
